### ISSUE TITLE
Exercício 2 - Respostas - Tarefas Técnicas

### ISSUE THREAD

**Issue by Natheebr** [Natheebr/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-22-1#12]
Tarefa 1- Configurar Sensores de Linha: Instalar e configurar os sensores de linha no robô Arduino, de modo que possam detectar a linha no chão.

Tarefa 2- Programação do Controlador: Desenvolver o código para o controlador do robô Arduino, de forma que ele seja capaz de interpretar os dados dos sensores de linha e tomar decisões para seguir a linha.

Tarefa 3- Calibração dos Sensores: Realizar a calibração dos sensores de linha para garantir que eles estejam ajustados corretamente e capazes de detectar a linha de maneira confiável.

Tarefa 4- Implementar Lógica de Controle: Desenvolver a lógica de controle que permitirá ao robô seguir a linha de maneira autônoma, tomando decisões como girar à esquerda, à direita ou manter-se na linha com base nas informações dos sensores.

Tarefa 5- Testes e Depuração: Testar o robô em um ambiente controlado, como um percurso com linha preta no chão, identificando e corrigindo possíveis problemas na programação e no hardware.

Tarefa 6- Otimização de Desempenho: Otimizar o código e o desempenho do robô para garantir uma resposta rápida aos desafios da pista e minimizar a latência.

Tarefa 7- Documentação e Instruções: Preparar documentação clara que explique como o robô foi projetado, como o código funciona e como os sensores foram configurados, para futuras referências.

Tarefa 8- Treinamento do Montador: Se o montador não tiver experiência técnica, fornecer treinamento básico sobre como operar o robô e fazer manutenção simples.

Tarefa 9- Suporte ao Usuário: Fornecer um meio de suporte ao usuário (neste caso, o montador do robô) para esclarecer dúvidas ou resolver problemas que possam surgir durante a operação do robô.

Tarefa 10- Detecção de Obstáculos: Caso a história não tenha especificado, adicionar sensores de obstáculos para que o robô possa evitar colidir com objetos que possam estar em seu caminho enquanto segue a linha.

Tarefa 11- Configurar Controles Manuais: Se necessário, implementar a capacidade de controlar manualmente o robô por meio de um controle remoto ou aplicativo, para situações em que a operação autônoma não seja desejada.

Tarefa 12- Bateria e Alimentação: Certificar-se de que o robô tenha uma fonte de alimentação adequada, como baterias, e implementar circuitos de proteção e carregamento para garantir a autonomia do robô.

Tarefa 13- Feedback Visual ou Sonoro: Adicionar recursos de feedback visual ou sonoro para indicar o status do robô, como LEDs ou alto-falantes que possam alertar sobre problemas ou sucesso na missão.

Tarefa 14- Integração com Plataforma de Controle: Se o projeto permitir, integrar o robô com uma plataforma de controle via smartphone ou computador para monitorar o progresso, ajustar configurações e coletar dados de desempenho.

Tarefa 15- Testes de Campo: Realizar testes de campo em diferentes tipos de superfícies e condições de iluminação para garantir que o robô seja robusto e capaz de seguir a linha de maneira confiável em cenários do mundo real.

Tarefa 16- Aprimoramentos e Otimizações Futuras: Preparar uma lista de possíveis melhorias ou otimizações futuras que possam ser feitas no robô, como a adição de sensores adicionais, atualizações de software ou melhorias no chassi.

**Comment by Natheebr** [comment]
Professor essas Tarefas Técnicas devem ser colocadas no GitHub Desktop ou aqui mesmo no comentário feito acima?

**Comment by HamiltonFilho** [comment]
A resposta do exercício pode ficar aqui mesmo

**Comment by HamiltonFilho** [comment]
A tarefa 7 é mais importante do que parece. O que mais precisa nesta tarefa?

As tarefas 8 e 9 fazem parte da sustentação, após a entrega formal do projeto

Tarefas 10, 11, 12, 13, 14, 15 e 16 são excelentes candidatos para novas histórias. Lembrem-se que não é prático ter uma única história que faça todo o projeto!

**Comment by Natheebr** [comment]
Blz, mas é só isso mesmo do exercício para fazer no momento?

**Comment by HamiltonFilho** [comment]
Por favor note que as modificações acima são necessárias para tornar a lista solicitada elegível como resposta para este exercício

Ainda existem questões em aberto, como a pergunta que fiz acima para a tarefa 7

**Comment by Natheebr** [comment]
Tarefa 7 - Documentação e Instruções:

A documentação e instruções desempenham um papel crucial em qualquer projeto, pois garantem que o conhecimento sobre o projeto seja transferido efetivamente e que outras pessoas possam entender e utilizar o que foi desenvolvido. Para tornar essa tarefa ainda mais eficaz, você deve incluir o seguinte:

Lista de Materiais: Enumere todos os componentes e peças usadas no projeto, incluindo informações sobre onde obtê-los.

Diagrama de Fiação: Forneça um diagrama claro de como todos os componentes estão conectados ao Arduino ou microcontrolador.

Código-Fonte: Disponibilize o código-fonte que controla o robô, devidamente comentado e organizado. Explique as principais funções e partes do código para que os outros possam entender e, se necessário, fazer modificações.

Explicação do Funcionamento: Descreva como o robô segue a linha e toma decisões com base nos sensores e no código. Explique os algoritmos ou lógica de controle usados.

Instruções de Montagem: Se o projeto requer montagem física, forneça um guia passo a passo para montar o robô, incluindo imagens ou diagramas, se possível.

Instruções de Uso: Explique como operar o robô de maneira clara e concisa, incluindo como ligá-lo, calibrá-lo (se necessário) e como iniciar o seguinte de linha.

Solução de Problemas: Forneça uma lista de problemas comuns que os usuários podem encontrar e suas soluções. Isso ajudará a solucionar problemas rapidamente.

Referências: Cite fontes de informações e recursos adicionais que possam ser úteis para quem trabalha no projeto.

Licença e Direitos Autorais: Especifique os termos de uso do projeto, incluindo informações sobre licenças de código-fonte ou qualquer propriedade intelectual associada ao projeto.

Contato para Suporte: Deixe informações de contato para que os usuários possam obter ajuda adicional, se necessário.

**Comment by HamiltonFilho** [comment]
Esta é uma mensagem para confirmar que este exercício foi considerado ENTREGUE COM SUCESSO pelo grupo, e isto irá refletir de forma positiva na nota A2 de todos os membros desta equipe
