### ISSUE TITLE
Subir código do projeto semestral

### ISSUE THREAD

**Issue by HamiltonFilho** [Natheebr/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-22-1#2]
Prezado grupo,

O código do projeto semestral, mesmo que parcial, deve ser upado neste repositório, conforme orientado em várias aulas

A partir de agora passarei a rastrear e avaliar as ações, e a falta de ação irá afetar negativamente a avaliação deste grupo

**Comment by HamiltonFilho** [comment]
Por favor tomar ação!

**Comment by Natheebr** [comment]
Ação praticada.
