### ISSUE TITLE
Limpeza de branches não utilizadas de DEV

### ISSUE THREAD

**Issue by HamiltonFilho** [Natheebr/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-22-1#3]
Prezado grupo,

Por favor manter o github limpo para branches não utilizadas!

Notei que existem branches de DEV usadas para testes, as quais devem ser apagadas

Lembrando que a branch DEV deve receber pull requests para capturar todo o codigo em desenvolvimento

**Comment by Natheebr** [comment]
Ação realizada em sala.
