### ISSUE TITLE
Atividade #1 - Habilitar DISCUSSIONS neste repositório

### ISSUE THREAD

**Issue by HamiltonFilho** [Natheebr/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-22-1#5]
Caro grupo,

Por favor habilitar a funcionalidade DISCUSSIONS neste repositório

O administrador do repositório deve clicar na aba Settings, e dentro da Aba General clicar no checkbox DISCUSSIONS

Esta atividade deve ser concluída o quanto antes!

![github-discussions](https://github.com/Natheebr/IT-BRAZIL-ACADEMY-SALTO-ADS-GRUPO-22-1/assets/28486980/bc32b565-6af4-488e-a84d-0c0f07876922)

**Comment by HamiltonFilho** [comment]
Por favor tomar ação neste item!

**Comment by Natheebr** [comment]
Ação tomada.
